name: Conference
author: RoboMWM
version: ${project.version}
main: me.robomwm.Conference.Conference
commands:
    join:
        usage: /join <conference>
    part:
        aliases: [leave, quit]
    c:
        usage: /c <message ...>
    invite:
        usage: /invite <player>
    conferenceadmin:
        usage: /conferenceadmin <delete|view|check|part> [player]
